### ISSUE TITLE
Bad error message on parsing '$...id'.

### ISSUE THREAD

**Issue by krajzeg** [dchester/jsonpath#33]
When parsing this erroneous path: `'$...id'` (and others like it), the result is not a friendly parse error, but a  TypeError from somewhere within jsonpath.

```
> var jp = require('jsonpath')
> jp.parse('$...id')
TypeError: Cannot read property 'initialize' of undefined
    at Object.parser.yy.parseError (/Users/wasyl/Projects/chap/chaplain/node_modules/jsonpath/lib/parser.js:10:18)
    at Object.parse (/Users/wasyl/Projects/chap/chaplain/node_modules/jsonpath/generated/parser.js:224:22)
    at JSONPath.parse (/Users/wasyl/Projects/chap/chaplain/node_modules/jsonpath/lib/index.js:19:22)
...
```

Adding an if in that line checking if `parser.yy.ast` is present before calling `initialize()` on it seems to fix that, but I'm not 100% sure that's the right fix.

**Comment by dchester** [comment]
Thanks -- looking better now.
