### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by zmorris** [dchester/jsonpath#99]
I tried the first example on repl.it 

```
var cities = [
  { name: "London", "population": 8615246 },
  { name: "Berlin", "population": 3517424 },
  { name: "Madrid", "population": 3165235 },
  { name: "Rome",   "population": 2870528 }
];

var jp = require('jsonpath');
var names = jp.query(cities, '$..name');

// [ "London", "Berlin", "Madrid", "Rome" ]
```

Output:

```
node v9.7.1 linux/amd64
   

Repl.it: Installing fresh packages
Repl.it: jsonpath


> jsonpath@1.0.0 postinstall /home/runner/node_modules/jsonpath
> node lib/aesprim.js > generated/aesprim-browser.js

+ jsonpath@1.0.0
added 30 packages in 4.892s


Repl.it: package installation success

AssertionError [ERR_ASSERTION]: obj needs to be an object
    at JSONPath.query (/home/runner/node_modules/jsonpath/lib/index.js:91:10)
    at evalmachine.<anonymous>:9:16
    at Script.runInContext (vm.js:74:29)
    at Object.runInContext (vm.js:182:6)
    at evaluate (/run_dir/repl.js:137:14)
    at Socket.<anonymous> (/run_dir/repl.js:120:5)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
```

Not sure what's going on, this could be a problem with repl.it itself.  Just thought you'd like to be aware of it in case jsonpath is making assumptions about the runtime environment that might not always be true.

Otherwise, looks like a pretty solid library, keep up the good work.

**Comment by zmorris** [comment]
Here's a workaround, using a wrapper function around [JSONPath Plus](https://github.com/s3u/JSONPath):

https://repl.it/repls/InsecureFlawlessDebuggers

```
const jp = {
  query: function (obj, pathExpression) {
    return require('jsonpath-plus')({json: obj, path: pathExpression});
  }
}

const cities = [
  { name: "London", "population": 8615246 },
  { name: "Berlin", "population": 3517424 },
  { name: "Madrid", "population": 3165235 },
  { name: "Rome",   "population": 2870528 }
];

const names = jp.query(cities, '$..name');

console.log(names);

// [ "London", "Berlin", "Madrid", "Rome" ]
```

Output:

```
node v9.7.1 linux/amd64
   

Repl.it: Installing fresh packages
Repl.it: jsonpath-plus

+ jsonpath-plus@0.16.0
added 1 package in 1.198s


Repl.it: package installation success

[ 'London', 'Berlin', 'Madrid', 'Rome' ]
=> undefined
```

Just add more utility functions to the `jp` variable as needed.  Node.js caches `require` so it's not a huge deal to call it over and over again for testing.  Real code could use a `const JSONPath = require('jsonpath-plus')` statement and then use `JSONPath` within the `jp` wrapper.

Hope this helps someone.

**Comment by Attrash-Islam** [comment]
That works in [Golden Path](https://github.com/Attrash-Islam/golden-path).


```js
import { get } from "golden-path";

const cities = [
  { name: "London", population: 8615246 },
  { name: "Berlin", population: 3517424 },
  { name: "Madrid", population: 3165235 },
  { name: "Rome", population: 2870528 }
];

const result = get("*.name", cities);

console.log({ result });
```

**Comment by KarelJakubec** [comment]
I can confirm the very same issue when I tried to run this inside Segment.io as part of custom function. When testing in localhost (node v12.19.0) works like a charm.

The workaround with using JSONPath Plus solved the issue, yet I would be curious why does this lib fail in certain (serverless ?) environments. A dependency on some lib?

**Comment by Ivan-Kouznetsov** [comment]
Still happens, in my case locally, not related to "serverless" environments
